spring.application.name=inventario-service

server.port=8081

# Configuración de H2
spring.datasource.url=jdbc:h2:mem:inventario_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita la consola web de H2 para ver tus tablas (localhost:8081/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

producto.service.url=${PRODUCTO_SERVICE_URL:http://host.docker.internal:8080/api/productos}
